fix: start script finds credhub jar
credhub failed to deploy with the error:
> Error: Unable to access jarfile *.jar

the double quotes around the *.jar caused the process to expect to find
a jar with that exact name rather than find the credhub.jar

changing this to credhub.jar is more explicit in our intention and
avoids the previous issue.