Change key name for credhub.encryption.providers
We have followed these examples, but when deploying the release got the following complaint from BOSH:
```
Error filling in template '/Users/pivotal/.bosh/installations/5115988c-ee8f-4d72-608b-5a072c3d097f/tmp/bosh-release-job725020671/templates/encryption.conf.erb' for credhub/0 (line 5: #<NoMethodError: undefined method `[]' for nil:NilClass>) (RuntimeError)
```
Looks like the key should be `name` instead of `provider_name`