Revert "Ensure ext directory exists before copying."
This reverts commit c64e512e058ef5e7abef4c4f0e13529a4e3ed299.

This bad commit introduced the following two error when deploying
Credhub.
  1)
  .<JAVA_HOME>/lib/ext exists, extensions mechanism no longer supported; Use -classpath instead.

  2)
  Error: Could not create the Java Virtual Machine.
  Error: A fatal exception has occurred. Program will exit.